Cygnus Language Generator (#160)
* initial changes

* install flex on docker

* included clg in cygnus

* some improvements

* removed docs.tar

* added clg files

* added flex and bison build support

* backup commit

* generates flex and bison from .cyl

* adding ctags

* minor tweaks

* intermediate commit

* restructured

* fixed sync issues and other fixes

* added bisonparser

* refactored code

* parser and lexer writer added

* review changes

* build failure fix

* func coverage fix

* fixed build command mismatch in gcc/g++

* some fixe

* build flex and bison outside src

* more coverage

* minor fixes

* added testcases

* temp commit

* fixed permissions

* fix coverage

* minor change

diff --git a/tools/cybuild b/tools/cybuild
--- a/tools/cybuild
+++ b/tools/cybuild
@@ -2,7 +2,9 @@
 
 source cmdline.bash    # command line parser
 
-declare BUILD_MODE=debug
+declare BUILD_MODE="debug"
+declare ERROR=0
+declare STRICT="no"
 
 OPTION['--clean']="value:bool,eval:BUILD_MODE=clean,help:clean generated files"
 OPTION['--coverage']="value:bool,eval:BUILD_MODE=coverage,help:create coverage build"
@@ -15,20 +17,16 @@ OPTION['--sanitize']="value:bool,eval:BUILD_MODE=sanitize,help:create sanitized 
 OPTION['--strict']="value:bool,eval:STRICT=yes,help:use strict options for compilation"
 
 MAKE() {
-    {
+    local make_force=""
     if [[ ${VALUES['--force']} ]]; then
-        make clean
+        make_force="-B"
     fi
 
-    if [[ ${VALUES['--strict']} ]]; then
-        make -q && make clean
-        make MODE=$1 STRICT=yes 2>$report_dir/${BUILD_MODE}-errors
-    else
-        make MODE=$1 2>$report_dir/${BUILD_MODE}-errors
-    fi
+    make -r $make_force MODE=$1 STRICT=$STRICT 3>&1 1>&2 2>&3 3>&- | tee $report_dir/${BUILD_MODE}-errors | tee logs/cybuild-${BUILD_MODE}.log
 
-    cat $report_dir/${BUILD_MODE}-errors
-    } | tee logs/cybuild-${BUILD_MODE}.log
+    if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
+        return 1
+    fi
 
     sed -i 's|\x1b\[[;0-9]*m\x1b\[K||g' $report_dir/${BUILD_MODE}-errors logs/cybuild-${BUILD_MODE}.log
 }
@@ -36,6 +34,7 @@ MAKE() {
 main() {
     parseCmdLine $@
     local errors=0
+    local warnings=0
     local report_dir="reports/compiler"
     mkdir -p $report_dir
     SECONDS=0
@@ -61,19 +60,34 @@ main() {
         sanitize)
             MAKE sanitize
             ;;
-        *)
-            MAKE debug
-            ;;
-    esac
+    esac || ERROR=1
 
     if [[ ! $BUILD_MODE == "clean" ]]; then
         build_time=$(TZ=UTC0 printf '%(%Hh:%Mm:%Ss)T\n' $SECONDS)
 
-        test -f $report_dir/${BUILD_MODE}-errors \
-            && errors=$(egrep -c "error:|warning:" $report_dir/${BUILD_MODE}-errors)
-        echo -e "\e[1;31mErrors|Warnings: $errors\e[m"
+        if [[ -f $report_dir/${BUILD_MODE}-errors ]]; then
+            errors=$(egrep -c "error:" $report_dir/${BUILD_MODE}-errors)
+            warnings=$(egrep -c "warning:" $report_dir/${BUILD_MODE}-errors)
+            if [[ $warnings -ne 0 ]]; then
+                echo -e "\e[1;33mWarnings: $warnings\e[m"
+                #if [[ ${VALUES['--strict']} ]]; then Enable it when compiler warnings are enabled
+                #    ERROR=1
+                #fi
+            fi
+            if [[ $errors -ne 0 ]]; then
+                echo -e "\e[1;31mErrors: $errors\e[m"
+                ERROR=1
+            fi
+        fi
+    fi
 
-        echo "$(du -h $CYGNUS_HOME/build/bin/$BUILD_MODE/cygnus-$BUILD_MODE | cut -f1) in $build_time"
+    if [[ $ERROR -eq 0 ]]; then
+        exe=$CYGNUS_HOME/build/bin/$BUILD_MODE/cygnus-$BUILD_MODE
+        test -f $exe && echo $(du -h $exe | cut -f1) in $build_time
+        echo -e "\e[1;32mSuccess\e[m"
+    else
+        echo -e "\e[1;31mFailed\e[m"
+        return 1
     fi
 }
 
diff --git a/tools/cyregress b/tools/cyregress
--- a/tools/cyregress
+++ b/tools/cyregress
@@ -7,7 +7,7 @@ declare -a valid_tests
 declare -a fail_list
 
 declare OUT_DIR='test_run'
-declare TEST_MODE=''
+declare TEST_MODE='debug'
 declare FUNC_COUNT=0
 declare UNIT_COUNT=0
 declare UNBUFF=''
@@ -32,13 +32,13 @@ OPTION['POS']='dest:test_list,count:0+'
 
 validateTests() {
     if [[ ${VALUES['-a']} ]]; then
-        test -d ${VALUES['-a']} || LOG EE "directory \`${VALUES['-a']}' does not exit";
+        test -d ${VALUES['-a']} || LOG EE "directory \`${VALUES['-a']}' does not exists";
         valid_tests=$(find ${VALUES['-a']} -type f -name "*.cyt" | xargs realpath)
     elif [[ ${VALUES['-f']} ]]; then
-        test -d ${VALUES['-f']} || LOG EE "directory \`${VALUES['-f']}' does not exit";
+        test -d ${VALUES['-f']} || LOG EE "directory \`${VALUES['-f']}' does not exists";
         valid_tests=$(find ${VALUES['-f']} -type f -path "*func*.cyt" | xargs realpath)
     elif [[ ${VALUES['-u']} ]]; then
-        test -d ${VALUES['-u']} || LOG EE "directory \`${VALUES['-u']}' does not exit";
+        test -d ${VALUES['-u']} || LOG EE "directory \`${VALUES['-u']}' does not exists";
         valid_tests=$(find ${VALUES['-u']} -type f -path "*unit*.cyt" | xargs realpath)
     else
         for test in ${VALUES["test_list"]}; do
@@ -91,7 +91,7 @@ runGDBTest() {
         FUNC_COUNT=$((FUNC_COUNT + 1))
         makeRunDir $testcase_dir $testcase
         cd $OUT_DIR/`dirname $testcase`
-        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
+        echo -e "\e[47m\e[30m[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt]\e[0m $testcase"
         source `basename $1`
         for pre_run in ${!PRE_RUN[@]}; do
             eval ${PRE_RUN[pre_run]}
@@ -105,7 +105,7 @@ runGDBTest() {
         UNIT_COUNT=$((UNIT_COUNT + 1))
         makeRunDir $testcase_dir $testcase
         cd $OUT_DIR/`dirname $testcase`
-        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
+        echo -e "\e[47m\e[30m[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt]\e[0m $testcase"
         source `basename $1`
         for pre_run in ${!PRE_RUN[@]}; do
             eval ${PRE_RUN[pre_run]}
@@ -126,6 +126,7 @@ runFuncTest() {
 }
 
 runUnitTest() {
+    pwd
     gen-make $(find $CYGNUS_HOME/include -mindepth 1 -type d -printf "-i %p ") -i $CYGNUS_HOME/src/base -i$CYGNUS_HOME/tests/utils/include $(find $CYGNUS_HOME/src -mindepth 1 -type d -printf "-s %p ") -s $CYGNUS_HOME/tests/utils/src unit.cc || return 1
     make --no-print-directory $TEST_MODE 2>&1 | tee make.log
     sed -i -e 's|\x1b\[[;0-9]*m\x1b\[K||g' -e 's/\x1b\[[0-9]+m//g' make.log
@@ -150,7 +151,7 @@ runTest() {
         FUNC_COUNT=$((FUNC_COUNT + 1))
         makeRunDir $testcase_dir $testcase
         cd $OUT_DIR/`dirname $testcase`
-        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
+        echo -e "\e[47m\e[30m[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt]\e[0m $testcase"
         source `basename $1`
         for pre_run in ${!PRE_RUN[@]}; do
             eval ${PRE_RUN[pre_run]}
@@ -164,7 +165,7 @@ runTest() {
         UNIT_COUNT=$((UNIT_COUNT + 1))
         makeRunDir $testcase_dir $testcase
         cd $OUT_DIR/`dirname $testcase`
-        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
+        echo -e "\e[47m\e[30m[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt]\e[0m $testcase"
         source `basename $1`
         for pre_run in ${!PRE_RUN[@]}; do
             eval ${PRE_RUN[pre_run]}
@@ -292,7 +293,7 @@ main() {
         CYGNUS=$CYGNUS_HOME/build/bin/cygnus
 
         if [[ ${VALUES['-a']} || ${VALUES['-f']} ]] && [[ ! -x $CYGNUS ]]; then
-            LOG EE "$CYGNUS does not exist"
+            LOG EE "$CYGNUS does not exists"
         fi
         rm -rf reports/func reports/unit
         mkdir -p reports/func reports/unit
@@ -308,6 +309,7 @@ main() {
         done
         return
     fi
+
     {
     if [[ $test_out == $OUT_DIR ]]; then
         LOG EE "test directory and out directory cannot be same"
@@ -355,7 +357,11 @@ main() {
     esac
 
     if [[ ${VALUES['-a']} || ${VALUES['-f']} ]] && [[ ! -x $CYGNUS ]]; then
-        LOG EE "$CYGNUS does not exist"
+        LOG I "Building: cygnus in $TEST_MODE mode"
+        cybuild --$TEST_MODE
+        if [[ $? -ne 0 ]]; then
+            LOG EE "Build failed"
+        fi
     fi
     rm -rf reports/func reports/unit
     mkdir -p reports/func reports/unit
@@ -381,8 +387,10 @@ main() {
                 mkdir -p reports/coverage/func
                 rm -f reports/coverage/func/coverage.info
                 for dir in $(find build/obj/coverage -mindepth 1 -type d); do
-                    lcov --gcov-tool=gcov-7 -c -b src/${dir#build/obj/coverage/} -d $dir -d include --no-external -q >> reports/coverage/func/coverage.info 2> /dev/null
+                    lcov -c -b src/${dir#build/obj/coverage/} -d $dir -d include --no-external -q >> reports/coverage/func/coverage.info
                 done
+                # remove *.c, *.l, *.y from coverage.info
+                sed -i '/.*\.[cly]$/,/end_of_record/ d' reports/coverage/func/coverage.info
                 GENHTML func
             fi
 
@@ -391,13 +399,13 @@ main() {
                 mkdir -p reports/coverage/unit
                 rm -f reports/coverage/unit/coverage.info
                 for dir in $(find src -mindepth 1 -type d); do
-                    lcov --gcov-tool=gcov-7 -b $dir -c -d $OUT_DIR -d include --no-external -q >> reports/coverage/unit/coverage.info 2> /dev/null
+                    lcov -b $dir -c -d $OUT_DIR -d include --no-external -q >> reports/coverage/unit/coverage.info
                 done
 
                 # Put missing files in coverage.info when all testcases in directory run
-                if [[ ${VALUES['-a']} ]]; then
+                if [[ ${VALUES['-a']} || ${VALUES['-u']} ]]; then
                     mkdir /tmp/cygnus_tmp -p
-                    find include src -regex ".*\.cc\|.*\.h\|.*\.tcc" | egrep -v "main.cc|cymem.cc" | sort -u | xargs realpath > /tmp/cygnus_tmp/all_files
+                    find src -regextype egrep -regex ".*\.(c|cc|h|tcc)" | egrep -v "main.cc|cymem.cc" | sort -u | xargs realpath > /tmp/cygnus_tmp/all_files
                     egrep "SF:" reports/coverage/unit/coverage.info  | sed 's/SF://' | sort -u > /tmp/cygnus_tmp/covered_files
                     comm -23 /tmp/cygnus_tmp/all_files /tmp/cygnus_tmp/covered_files > /tmp/cygnus_tmp/uncovered_files
                     {
