fixed sync issues and other fixes

diff --git a/tools/cybuild b/tools/cybuild
--- a/tools/cybuild
+++ b/tools/cybuild
@@ -25,12 +25,13 @@ MAKE() {
 
     if [[ ${VALUES['--strict']} ]]; then
         make -q && make clean
-        make MODE=$1 STRICT=yes 2>$report_dir/${BUILD_MODE}-errors
+        make MODE=$1 STRICT=yes 3>&1 1>&2 2>&3 3>&- | tee $report_dir/${BUILD_MODE}-errors
     else
-        make MODE=$1 2>$report_dir/${BUILD_MODE}-errors
+        #make MODE=$1 2>$report_dir/${BUILD_MODE}-errors
+        make MODE=$1 3>&1 1>&2 2>&3 3>&- | tee $report_dir/${BUILD_MODE}-errors
     fi
 
-    cat $report_dir/${BUILD_MODE}-errors
+    echo "ERROR: "
     } | tee logs/cybuild-${BUILD_MODE}.log
 
     sed -i 's|\x1b\[[;0-9]*m\x1b\[K||g' $report_dir/${BUILD_MODE}-errors logs/cybuild-${BUILD_MODE}.log
