implemented multple diffs and improved fa.cyt

diff --git a/tools/cyregress b/tools/cyregress
--- a/tools/cyregress
+++ b/tools/cyregress
@@ -68,7 +68,6 @@ makeRunDir(){
 }
 
 runFuncTest() {
-    source `basename $1`
     {
     for i in ${!CASE[@]}; do
         echo "|CASE $((i+1))| $(echo ${CASE[$i]} | sed "s|$CYGNUS|cygnus|")"
@@ -82,6 +81,73 @@ runUnitTest() {
     gen-make -i $CYGNUS_HOME/include/base -i $CYGNUS_HOME/include/scanner -i $CYGNUS_HOME/include/utils -i $CYGNUS_HOME/src/base/tcc -i $CYGNUS_HOME/tests/utils/include -s $CYGNUS_HOME/src/base -s $CYGNUS_HOME/src/scanner -s $CYGNUS_HOME/tests/utils/src test.cc || return 1
     make --no-print-directory $TEST_MODE 2>&1 | TEE make.log || return 1
     $tool ./test 2>&1 > TESTLOG || return 1
+}
+
+runTest() {
+    local test=$1
+    declare -A DIFFS
+    if [[ $test =~ func.*cyt ]]; then
+        local testcase=$(echo $test | egrep -o "func.*cyt")
+        local testcase_dir=${test%/$testcase}
+        FUNC_COUNT=$((FUNC_COUNT + 1))
+        makeRunDir $testcase_dir $testcase
+        cd $OUT_DIR/`dirname $testcase`
+        echo "|TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt | $testcase"
+        source `basename $1`
+        runFuncTest $testcase || ret=1
+    else
+        local testcase=$(echo $test | egrep -o "unit.*cyt")
+        local testcase_dir=${test%/$testcase}
+        UNIT_COUNT=$((UNIT_COUNT + 1))
+        makeRunDir $testcase_dir $testcase
+        cd $OUT_DIR/`dirname $testcase`
+        echo "|TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt | $testcase"
+        source `basename $1`
+        runUnitTest $testcase || ret=1
+    fi
+
+    local status=1
+    for ref in ${!DIFFS[@]}; do
+        diff -N --color=always $ref ${DIFFS[$ref]}
+        if [[ $? -ne 0 || $ret -eq 1 ]]; then
+            status=0
+            if [[ ${VALUES['-r']} ]]; then
+                cp ${DIFFS[$ref]} $ref
+                echo "$ref updated"
+            fi
+        fi
+    done
+
+    if [[ $status -eq 1 ]]; then
+        echo "status: PASS"
+    else
+        echo "status: FAIL"
+        fail_cnt=$((fail_cnt + 1))
+    fi
+
+    case $TEST_MODE in
+        mem-check)
+            if [[ $(egrep -c "ERROR SUMMARY: 0 errors" valgrind.out) -ne 1 ]]; then
+                sed -nr -e 's/^=+[0-9]+=+ //' -e '/HEAP SUMMARY/,/LEAK SUMMARY/ p' valgrind.out | sed -e '/HEAP SUMMARY:\|LEAK SUMMARY:/,/^$/ d'  | \
+                while IFS= read line; do
+                    if [[ $line == "" ]]; then
+                        checksum=$(echo $error | md5sum | egrep -o "[0-Z]+")
+                        echo "CHECKSUM: $checksum" >> mem.err
+                        echo -e "$error" >> mem.err
+                        error=""
+                        continue
+                    fi
+                    error="    ${line/#   /}\n$error"
+                done
+                echo "mem-error: $(egrep -c "CHECKSUM: " mem.err)"
+            fi
+            ;;
+        perf)
+            callgrind_annotate --threshold=100 callgrind.out | egrep "$CYGNUS_HOME/src/" | gen-perf > TESTPERF
+            perf-diff REFPERF TESTPERF | tee perf.diff
+            ;;
+    esac
+    cd - > /dev/null
 }
 
 main() {
@@ -155,59 +221,7 @@ main() {
     for test in $valid_tests; do
         ret=0
         echo
-        if [[ $test =~ func.*cyt ]]; then
-            local testcase=$(echo $test | egrep -o "func.*cyt")
-            local testcase_dir=${test%/$testcase}
-            FUNC_COUNT=$((FUNC_COUNT + 1))
-            makeRunDir $testcase_dir $testcase
-            cd $OUT_DIR/`dirname $testcase`
-            echo "|TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt | $testcase"
-            runFuncTest $testcase || ret=1
-        else
-            local testcase=$(echo $test | egrep -o "unit.*cyt")
-            local testcase_dir=${test%/$testcase}
-            UNIT_COUNT=$((UNIT_COUNT + 1))
-            makeRunDir $testcase_dir $testcase
-            cd $OUT_DIR/`dirname $testcase`
-            echo "|TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt | $testcase"
-            runUnitTest $testcase || ret=1
-        fi
-
-        diff -N --color=always REFLOG TESTLOG
-        if [[ $? -ne 0 || $ret -eq 1 ]]; then
-            echo "status: FAIL"
-            fail_cnt=$((fail_cnt + 1))
-            if [[ ${VALUES['-r']} ]]; then
-                cp TESTLOG REFLOG
-                echo "REFLOG updated"
-            fi
-        else
-            echo "status: PASS"
-        fi
-
-        case $TEST_MODE in
-            mem-check)
-                if [[ $(egrep -c "ERROR SUMMARY: 0 errors" valgrind.out) -ne 1 ]]; then
-                    sed -nr -e 's/^=+[0-9]+=+ //' -e '/HEAP SUMMARY/,/LEAK SUMMARY/ p' valgrind.out | sed -e '/HEAP SUMMARY:\|LEAK SUMMARY:/,/^$/ d'  | \
-                    while IFS= read line; do
-                        if [[ $line == "" ]]; then
-                            checksum=$(echo $error | md5sum | egrep -o "[0-Z]+")
-                            echo "CHECKSUM: $checksum" >> mem.err
-                            echo -e "$error" >> mem.err
-                            error=""
-                            continue
-                        fi
-                        error="    ${line/#   /}\n$error"
-                    done
-                    echo "mem-error: $(egrep -c "CHECKSUM: " mem.err)"
-                fi
-                ;;
-            perf)
-                callgrind_annotate --threshold=100 callgrind.out | egrep "$CYGNUS_HOME/src/" | gen-perf > TESTPERF
-                perf-diff REFPERF TESTPERF | tee perf.diff
-                ;;
-        esac
-        cd - > /dev/null
+        runTest $test
     done
     echo -e "\nSummary:"
     echo "    RUN:  $tc_cnt"
