Enable sanitization (#210)
* fixed python version issues

* gdb support added in cyregress

* adding color in sanitize output

* fixed sanitize error, ignored tags and cscope file

* enable sanitization checks in circleci

diff --git a/tools/cyregress b/tools/cyregress
--- a/tools/cyregress
+++ b/tools/cyregress
@@ -10,6 +10,7 @@ declare OUT_DIR='test_run'
 declare TEST_MODE=''
 declare FUNC_COUNT=0
 declare UNIT_COUNT=0
+declare UNBUFF=''
 
 GENHTML() {
     genhtml --ignore-errors source reports/coverage/$1/coverage.info --output-directory reports/coverage/$1/html --demangle-cpp --css-file .internal/coverage.css -t "$1 coverage" --legend --rc genhtml_hi_limit=98 --rc genhtml_med_limit=90 > reports/coverage/$1/genhtml.log 2> /dev/null
@@ -23,6 +24,7 @@ OPTION['-r']='value:bool,help:reflog update'
 OPTION['-u']='value:string,metavar:dir,without:-a,help:run unit tests only from <dir>'
 OPTION['--coverage']='value:bool,eval:TEST_MODE=coverage,help:run coverage tests'
 OPTION['--debug']='value:bool,eval:TEST_MODE=debug,help:run mem-check tests'
+OPTION['--gdb']='value:bool,without:--coverage --mem-check --perf --sanitize,help:run test with gdb'
 OPTION['--mem-check']='value:bool,eval:TEST_MODE=mem-check,help:run mem-check tests'
 OPTION['--perf']='value:bool,eval:TEST_MODE=perf,help:run mem-check tests'
 OPTION['--sanitize']='value:bool,eval:TEST_MODE=sanitize,help:run sanitization tests'
@@ -63,11 +65,62 @@ makeRunDir(){
     ln -rs $testcase_dir/`dirname $testcase`/* $test_out/ || return 1
 }
 
+runGDBFuncTest() {
+    for i in ${!CASE[@]}; do
+        echo "[CASE $((i+1))] $(echo ${CASE[$i]} | sed "s|$CYGNUS|cygnus|")"
+        gdb -q --args ${CASE[$i]}
+        echo
+    done
+}
+
+runGDBUnitTest() {
+    gen-make $(find $CYGNUS_HOME/include -mindepth 1 -type d -printf "-i %p ") -i $CYGNUS_HOME/src/base -i$CYGNUS_HOME/tests/utils/include $(find $CYGNUS_HOME/src -mindepth 1 -type d -printf "-s %p ") -s $CYGNUS_HOME/tests/utils/src unit.cc || return 1
+    make --no-print-directory $TEST_MODE
+    gdb -tui -q ./unit
+    echo
+}
+
+runGDBTest() {
+    local test=$1
+    declare -a CASES=()
+    declare -a PRE_RUN=()
+
+    if [[ $test =~ func.*cyt ]]; then
+        local testcase_dir=${test%/func*cyt}
+        local testcase=${test#$testcase_dir/}
+
+        FUNC_COUNT=$((FUNC_COUNT + 1))
+        makeRunDir $testcase_dir $testcase
+        cd $OUT_DIR/`dirname $testcase`
+        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
+        source `basename $1`
+        for pre_run in ${!PRE_RUN[@]}; do
+            eval ${PRE_RUN[pre_run]}
+        done
+
+        runGDBFuncTest $testcase
+    else
+        local testcase_dir=${test%/unit*cyt}
+        local testcase=${test#$testcase_dir/}
+
+        UNIT_COUNT=$((UNIT_COUNT + 1))
+        makeRunDir $testcase_dir $testcase
+        cd $OUT_DIR/`dirname $testcase`
+        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
+        source `basename $1`
+        for pre_run in ${!PRE_RUN[@]}; do
+            eval ${PRE_RUN[pre_run]}
+        done
+
+        runGDBUnitTest $testcase
+    fi
+}
+
 runFuncTest() {
     {
     for i in ${!CASE[@]}; do
         echo "[CASE $((i+1))] $(echo ${CASE[$i]} | sed "s|$CYGNUS|cygnus|")"
-        $tool ${CASE[$i]} | sed 's/.*/>   &/' || return 1
+        $UNBUFF $tool ${CASE[$i]} | sed 's/.*/>   &/' || return 1
         echo
     done
     } 2>&1 > TESTLOG
@@ -78,7 +131,7 @@ runUnitTest() {
     make --no-print-directory $TEST_MODE 2>&1 | tee make.log
     sed -i -e 's|\x1b\[[;0-9]*m\x1b\[K||g' -e 's/\x1b\[[0-9]+m//g' make.log
     {
-    $tool ./unit | sed -e '/\[CASE/! s/.*/>   &/' -e ' 2,$ s/\[CASE/\n[CASE/' || return 1
+    $UNBUFF $tool ./unit | sed -e '/\[CASE/! s/.*/>   &/' -e ' 2,$ s/\[CASE/\n[CASE/' || return 1
     echo
     } 2>&1 > TESTLOG 
 }
@@ -121,9 +174,9 @@ runTest() {
         runUnitTest $testcase || status=1
     fi
 
-    #---------------#
-    #  SORT_OUTPUT  #
-    #---------------#
+    #-------------#
+    # SORT_OUTPUT #
+    #-------------#
     if [[ $((${#SORT_OUTPUT[@]}%3)) -eq 0 ]]; then
         for i in $(eval echo {0..$((${#SORT_OUTPUT[@]}-1))..3}); do
             local case=${SORT_OUTPUT[$i]}
@@ -222,9 +275,41 @@ runTest() {
 main() {
     mkdir -p logs
     parseCmdLine $@
-    {
     OUT_DIR=${VALUES['-o']:-$OUT_DIR} 
     validateTests
+    
+    if [[ ${VALUES['--gdb']} ]]; then
+        if [[ $test_out == $OUT_DIR ]]; then
+            LOG EE "test directory and out directory cannot be same"
+        fi
+        echo "    OUT_DIR: $OUT_DIR"
+
+        tc_cnt=0
+        for test in $valid_tests; do
+            tc_cnt=$((tc_cnt + 1))
+        done
+        echo -e "\nGenerated Testcase: $tc_cnt"
+
+        CYGNUS=$CYGNUS_HOME/build/bin/cygnus
+
+        if [[ ${VALUES['-a']} || ${VALUES['-f']} ]] && [[ ! -x $CYGNUS ]]; then
+            LOG EE "$CYGNUS does not exist"
+        fi
+        rm -rf reports/func reports/unit
+        mkdir -p reports/func reports/unit
+        export fail_cnt=0
+
+        #-----------#
+        #    Run    #
+        #-----------#
+        for test in $valid_tests; do
+            ret=0
+            echo
+            runGDBTest $test
+        done
+        return
+    fi
+    {
     if [[ $test_out == $OUT_DIR ]]; then
         LOG EE "test directory and out directory cannot be same"
     fi
@@ -276,6 +361,7 @@ main() {
     rm -rf reports/func reports/unit
     mkdir -p reports/func reports/unit
     export fail_cnt=0
+    test -f /usr/bin/unbuffer && UNBUFF='/usr/bin/unbuffer'
 
     #-----------#
     #    Run    #
@@ -286,9 +372,9 @@ main() {
         runTest $test
     done
 
-    #-----------#
-    # Post Run  #
-    #-----------#
+    #------------#
+    #  Post Run  #
+    #------------#
     case $TEST_MODE in
         coverage)
             if [[ $FUNC_COUNT -gt 0 ]]; then
