Test run (#30) fixes #15
* configure circleci to run unit test
* adding machine in unit-test
* adding option -a in cytest
* adding LOG in cytest, check dir existence check in -d
* fixing errors

diff --git a/tools/cytest b/tools/cytest
--- a/tools/cytest
+++ b/tools/cytest
@@ -4,23 +4,56 @@ declare -a valid_list
 declare -a valid_tests
 declare -A option
 declare -A values
-ERR='[ERR]'
-INF='[INF]'
-WRN='[WRN]'
+declare EXITCODE=0
 
-#defaults
+# DEFAULTS
 test_dir='.'
 out_dir='test_run'
 
+####################################################################
+# How to create new option                                         #
+#   * help      : create help statement spaces are replacec by .   #
+#   * metavar   : string to be displayed for option argument       #
+#   * value     : type of value                                    #
+#                   bool    - no argument                          #
+#                   string  - option expects single argument       #
+#   * with      : mention dependency of option                     #
+####################################################################
+option['-a']="value=bool with=-d help=pick.testcases.from.directory.in.-d"
 option['-d']="value=string metavar=dir help=test.case.directory"
 option['-h']="value=bool help=help"
 option['-o']="value=string metavar=dir help=output.directory.of.test.run"
+
+EXIT(){
+    exit $EXITCODE
+}
+
+LOG(){
+    local msg=${2:?"message missing."}
+    case $1 in
+        E)
+            echo "[ERROR] $msg"
+            EXITCODE=1
+            ;;
+        I)
+            echo "[INFO] $msg"
+            ;;
+        W)
+            echo "[WARN] $msg"
+            ;;
+        *)
+            LOG E "unrecognized log type"
+            EXIT
+            ;;
+    esac
+}
 
 usage(){
     echo "USAGE: `basename $0` [options] [file...]"
     for opt in ${!option[@]}; do
         m=''
         h=''
+        mst=''
         for param in ${option[$opt]}; do
             case $param in
                 metavar=*)
@@ -29,15 +62,18 @@ usage(){
                 help=*)
                     h=${param#*=}
                     ;;
+                with=*)
+                    mst=", depends on ${param#*=}"
+                    ;;
             esac
         done
-        echo "    $opt $m: ${h//./ }"
+        echo "    $opt $m: ${h//./ } $mst"
     done
-    exit
+    EXIT
 }
 
 optionError(){
-    echo "$ERR option \`$1' expects argument"
+    LOG E "option \`$1' expects argument"
     for param in ${option[$1]};do
         case $param in
             metavar=*)
@@ -46,16 +82,21 @@ optionError(){
             help=*)
                 h=${param#*=}
                 ;;
+            with=*)
+                mst=", depends on ${param#*=}"
+                ;;
         esac
     done
     if [[ -z $h ]]; then
-        echo "$WRN short help for option \`$1' is missing."
+        LOG W "short help for option \`$1' is missing."
     else
-            echo "    $1 $m: ${h//./ }"
+            echo "    $1 $m: ${h//./ } $mst"
     fi
 }
 
 parseCmdLine() {
+    declare -A must
+
     while [ $1 ]; do
         opt=$1
         dest=''
@@ -78,10 +119,16 @@ parseCmdLine() {
                             val="true"
                         fi
                         ;;
+                    with=*)
+                        local deps=${param#*=}
+                        for o in ${deps//,/ }; do
+                            must["$o"]=$opt
+                        done
+                        ;;
                     metavar=*|help=*)
                         ;;
                     *)
-                        echo "$WRN invalid parameter $param defined in option \`$opt'"
+                        LOG W "invalid parameter $param defined in option \`$opt'"
                         error=1
                         continue
                         ;;
@@ -91,7 +138,7 @@ parseCmdLine() {
                 values[$opt]=$val
             fi
         elif [[ $1 =~ ^- ]]; then
-            echo "$INF ignoring unknown option \`$opt'"
+            LOG I "ignoring unknown option \`$opt'"
         else
             pos+=" $opt"
         fi
@@ -106,24 +153,43 @@ parseCmdLine() {
         usage
     fi
 
+    for o in ${!must[@]}; do
+        if [[ -z ${values[$o]} ]]; then
+            LOG E "option\[s\] $o is missing needed by ${must[$o]}"
+            optionError ${must[$o]}
+        fi
+    done
+
     for i in ${!values[@]}; do
         echo "$i: ${values[$i]}"
     done
 }
 
 validateTests() {
-    for test in ${values["test_list"]}; do
-        if [[ $test =~ unit.*\.cyt && -a $test_dir/$test ]]; then
-            valid_tests+=" $test"
-        else
-            echo "$WRN [invalid testcase] $test"
-            continue
+    if [[ ${values["-a"]} ]]; then
+        if [[ ${values["test_list"]} ]]; then
+            echo -e "$IGN -a is given, ignoring ${values["test_list"]}"
         fi
-    done
-    
-    if [[ -z $valid_tests ]]; then
-      echo "$ERR testcases missing"
-      exit 1
+        test -d $test_dir && cd $test_dir
+        valid_tests=`find -type f -path "unit*.cyt" | sed 's|./||'`
+        cd - > /dev/null
+        if [[ -z $valid_tests ]]; then
+            LOG W "no testcases found in directory: $test_dir"
+            EXIT
+        fi
+    else
+        for test in ${values["test_list"]}; do
+            if [[ $test =~ unit.*\.cyt && -a $test_dir/$test ]]; then
+                valid_tests+=" $test"
+            else
+                LOG W "[invalid testcase] $test"
+                continue
+            fi
+        done
+        if [[ -z $valid_tests ]]; then
+          LOG E "testcases missing"
+          EXIT
+        fi
     fi
 }
 
@@ -155,9 +221,10 @@ main() {
     echo test_dir: $test_dir
     echo out_dir : $out_dir
 
+    test -d $test_dir || LOG E "directory \`$test_dir' does not exit"
     if [[ $test_out == $out_dir ]]; then
-        echo $ERR test directory and out directory cannot be same
-        exit 1
+        LOG E "test directory and out directory cannot be same"
+        EXIT
     fi
     validateTests
 
