sanitize report fix

diff --git a/tools/gen-report b/tools/gen-report
--- a/tools/gen-report
+++ b/tools/gen-report
@@ -18,20 +18,6 @@ covReport() {
     echo
 }
 
-memReport() {
-    echo "Memory Report::"
-    test -f reports/mem-check/func/errors && echo "    Functional: $(adder $(egrep -o "[0-9] errors" reports/mem-check/func/errors | sed 's/ errors//'))" || echo "    Functional: -1"
-    test -f reports/mem-check/unit/errors && echo "    Unit: $(adder $(egrep -o "[0-9] errors" reports/mem-check/unit/errors | sed 's/ errors//'))" || echo "   Unit: -1"
-    echo
-}
-
-warnReport() {
-    echo "Compiler Warnings::"
-    test -f reports/warnings/debug-errors && echo "    Debug: $(egrep -c "warning: " reports/warnings/debug-errors)" || echo "    Debug: -1" 
-    test -f reports/warnings/release-errors && echo "    Release: $(egrep -c "warning: " reports/warnings/release-errors)" || echo "    Release: -1" 
-    echo ""
-}
-
 docsReport() {
     echo "DOCS::"
     echo "Status:"
@@ -39,6 +25,35 @@ docsReport() {
     echo ""
     echo "Undocumented:"
     test -f reports/docs/undoc && cat reports/docs/undoc
+    echo
+}
+
+memReport() {
+    echo "Memory Report::"
+    test -f reports/mem-check/func/errors && echo "    Functional: $(adder $(egrep -o "[0-9] errors" reports/mem-check/func/errors | sed 's/ errors//'))" || echo "    Functional: -1"
+    test -f reports/mem-check/unit/errors && echo "    Unit: $(adder $(egrep -o "[0-9] errors" reports/mem-check/unit/errors | sed 's/ errors//'))" || echo "   Unit: -1"
+    echo
+}
+
+sanitizationReport() {
+    echo "Sanitization Report::"
+    if [[  $(find test_run/sanitize/func -name "run.log" | xargs egrep -c "ERROR: ") -eq 0 ]]; then
+        echo "    Functioncal: PASS"
+    else
+        echo "    Functional: FAIL"
+    fi
+    if [[  $(find test_run/sanitize/unit -name "run.log" | xargs egrep -c "ERROR: ") -eq 0 ]]; then
+        echo "    Unit: PASS"
+    else
+        echo "    Unit: FAIL"
+    fi
+    echo
+}
+
+warnReport() {
+    echo "Compiler Warnings::"
+    test -f reports/warnings/debug-errors && echo "    Debug: $(egrep -c "warning: " reports/warnings/debug-errors)" || echo "    Debug: -1" 
+    test -f reports/warnings/release-errors && echo "    Release: $(egrep -c "warning: " reports/warnings/release-errors)" || echo "    Release: -1" 
     echo ""
 }
 
@@ -61,13 +76,14 @@ perfReport() {
 
 main() {
     parseCmdLine $@
-    docsReport
-    unitReport
-    warnReport
-    lintReport
     covReport
+    docsReport
+    lintReport
     memReport
     perfReport
+    sanitizationReport
+    unitReport
+    warnReport
     EXIT
 }
 
